export const CURRENT_CUSTOMER = 'CURRENT_CUSTOMER';

export const FETCH_CUSTOMER_REQUEST = 'FETCH_CUSTOMER_REQUEST';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';
export const FETCH_CUSTOMER_FAILURE = 'FETCH_CUSTOMER_FAILURE';

export const ADD_CUSTOMER_REQUEST = 'ADD_CUSTOMER_REQUEST';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAILURE = 'ADD_CUSTOMER_FAILURE';

export const EDIT_CUSTOMER_REQUEST = 'EDIT_CUSTOMER_REQUEST';
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_FAILURE = 'EDIT_CUSTOMER_FAILURE';

export const ADD_CUSTOMER_PHOTO_REQUEST = 'ADD_CUSTOMER_PHOTO_REQUEST';
export const ADD_CUSTOMER_PHOTO_SUCCESS = 'ADD_CUSTOMER_PHOTO_SUCCESS';
export const ADD_CUSTOMER_PHOTO_FAILURE = 'ADD_CUSTOMER_PHOTO_FAILURE';
